# Generated by Django 5.0.6 on 2024-05-22 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rental', '0004_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
