# Generated by Django 5.0.6 on 2024-07-13 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rental', '0004_user_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='image',
        ),
        migrations.RemoveField(
            model_name='car',
            name='original_price',
        ),
    ]
