# Generated by Django 5.0.6 on 2024-07-17 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rental', '0005_remove_car_image_remove_car_original_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='carimage',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
