# Generated by Django 5.0.6 on 2024-07-22 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rental', '0007_historicalcar_historicalcarcolor_historicalcarimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalcarcolor',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalcarimage',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalrental',
            name='car',
        ),
        migrations.RemoveField(
            model_name='historicalrental',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalrental',
            name='renter',
        ),
        migrations.RemoveField(
            model_name='historicalsale',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='historicalsale',
            name='car',
        ),
        migrations.RemoveField(
            model_name='historicalsale',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='HistoricalCar',
        ),
        migrations.DeleteModel(
            name='HistoricalCarColor',
        ),
        migrations.DeleteModel(
            name='HistoricalCarImage',
        ),
        migrations.DeleteModel(
            name='HistoricalRental',
        ),
        migrations.DeleteModel(
            name='HistoricalSale',
        ),
        migrations.DeleteModel(
            name='HistoricalUser',
        ),
    ]
