# Generated by Django 5.0.6 on 2024-07-24 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rental', '0011_transaction_rental_transaction_sale_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sales_rental.transaction'),
        ),
    ]
