# Generated by Django 5.0.6 on 2024-07-24 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rental', '0014_alter_rental_transaction_alter_sale_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='transaction',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
