# Generated by Django 5.0.6 on 2024-07-24 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rental', '0016_rental_amount_sale_amount_paymentdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdetails',
            name='description',
        ),
    ]
