# Generated by Django 5.0.6 on 2024-07-24 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rental', '0017_remove_paymentdetails_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetails',
            name='car',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payment_details', to='sales_rental.car'),
            preserve_default=False,
        ),
    ]
