# Generated by Django 5.0.6 on 2024-07-24 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rental', '0018_paymentdetails_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetails',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_details', to='sales_rental.car'),
        ),
    ]
