# Generated by Django 5.0.6 on 2024-07-24 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rental', '0019_alter_paymentdetails_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='colors',
        ),
        migrations.DeleteModel(
            name='CarColor',
        ),
    ]
