# Generated by Django 5.0.7 on 2024-07-25 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rental', '0020_remove_car_colors_delete_carcolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='carimage',
            name='car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sales_rental.car'),
            preserve_default=False,
        ),
    ]
