# Generated by Django 5.0.7 on 2024-07-25 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rental', '0021_carimage_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carimage',
            name='car',
        ),
    ]
