# Generated by Django 5.0.7 on 2024-07-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rental', '0022_remove_carimage_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetails',
            name='transaction_type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
