# Generated by Django 5.0.7 on 2024-07-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rental', '0023_paymentdetails_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='cancellation_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
