# Generated by Django 5.0.7 on 2024-07-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rental', '0024_rental_cancellation_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='cancellation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
